global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'arbitrage-bot'
    static_configs:
      - targets: ['test:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'geth'
    static_configs:
      - targets: ['geth:6060']
    metrics_path: '/debug/metrics/prometheus'
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # alertmanager:9093

rule_files:
  # - "rules/*.yml"
