global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'arbitrage-bot'
    static_configs:
      - targets: ['test:8000']
    metrics_path: '/metrics'

  - job_name: 'geth'
    static_configs:
      - targets: ['geth:6060']
    metrics_path: '/debug/metrics/prometheus'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'process'
    static_configs:
      - targets: ['test:8000']
    metrics_path: '/metrics/process'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
